require("__frozen-food-and-more__.prototypes.compat.boompuff-agriculture-updates")
require("__frozen-food-and-more__.prototypes.compat.fluroflux-updates")
require("__frozen-food-and-more__.prototypes.compat.vulcanus-sulfuric-bacteria-updates")
require("__frozen-food-and-more__.prototypes.tweaks.bioprocessing-tab-updates")
require("__frozen-food-and-more__.prototypes.tweaks.import-location-updates")
